### **Creating arrays**

In [5]:
import numpy as np
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [9]:
print(arr_list1.ndim)

1


In [10]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [11]:
print(arr_list1_2.ndim)

2


In [15]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1, list2, list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
print(arr_list1_3.ndim)

3
