### Numpy array attributes

In [2]:
import numpy as np
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [3]:
print("Shape", arr1.shape)
print("Size", arr1.size)
print("dType", arr1.dtype)
print('n_dim', arr1.ndim)

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [9]:
arr2 = np.array([[[1,2,3], [4,5,6],[7,8,9]]])
print(arr2)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
print("Shape", arr2.shape)
print("Size", arr2.size)
print("dType", arr2.dtype)
print('n_dim', arr2.ndim)

Shape (1, 3, 3)
Size 9
dType int64
n_dim 3


In [17]:
arr3 = np.array([1,2,3])
print(arr3)

[1 2 3]


In [15]:
print("Shape", arr3.shape)
print("Size", arr3.size)
print("dType", arr3.dtype)
print('n_dim', arr3.ndim)

Shape (3,)
Size 3
dType int64
n_dim 1
