### Array initialization method

In [ ]:
import numpy as np

# zeros array

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# ones array

one_arr = np.ones((1,3))
print(one_arr)


[[1. 1. 1.]]


In [ ]:
# Full array

full_arr = np.full((3,2), 9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]


In [ ]:
# Identity Matrix

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#  empty array
print(np.empty(2))

[4.94065646e-324 6.75541058e-310]


In [ ]:
#  evenly spaced array
print(np.arange(2,10,2))


[2 4 6 8]


In [ ]:
# specific number of equally spaced values between a range
print(np.linspace(2,10,4))


[ 2.          4.66666667  7.33333333 10.        ]


In [ ]:
# random values array - float
r_rr = np.random.rand(3,2)
print(r_rr)

[[0.31732198 0.61854299]
 [0.67796778 0.33849037]
 [0.9474166  0.58580821]]


In [ ]:
# random values array -int
rint_arr = np.random.randint(1,100,(3,3))
print(rint_arr)

[[28 15 10]
 [76 52 16]
 [17 31 74]]
