<a href="https://colab.research.google.com/github/mukund1040/NumPy-Learning-Journey/blob/main/04_array_index_%26_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array Indexing and Slicing

In [ ]:
import numpy as np

a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [ ]:
print(a[0])
print(a[1])
print(a[4])
print(a[-1])

1
3
9
9


In [ ]:
a = np.array([1,3,5,7,9])
print(a)
# Slicing :
# array[start:stop:step]
# stop - index, that is not included in output

[1 3 5 7 9]


In [ ]:
print(a[0:3])      # First 3 elements

[1 3 5]


In [ ]:
print(a[-3:]) # Last 3 elements

[5 7 9]


In [ ]:
print(a[0::2]) # All alternative elements with steps

[1 5 9]


In [ ]:
# Indexing on 2 Dimensional Array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

# 2D Array: [rows, columns]                   # 2D Array takes 2 values - rows and columns for indexing
# 3D Array: [layers/height, rows, columns]    # 3D Array takes 3 values - height, rows and columns for indexing

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2[0]) # first row
print(arr2[1]) # second row

[1 2 3]
[4 5 6]


In [ ]:
# slicing on 2D array
print(arr2[0][0])
print(arr2[0][1])
print(arr2[0][2])
print(arr2[1][0])
print(arr2[1][1])

1
2
3
4
5


In [ ]:
print(arr2[1]) # specific element - 1D
print(arr2[1:]) # slicing part - 2D

[4 5 6]
[[4 5 6]]


In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2[:, 0])       # 1st column
print(arr2[:, 1])       # 2nd column
print(arr2[:, 2])       # 3rd column

[1 4]
[2 5]
[3 6]


In [ ]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)
print(arr3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [ ]:
print(arr3[:, 0]) # 1st col value
print(arr3[:, 1]) # 2nd col value
print(arr3[:, 2]) # 3rd col value

[1 4 7]
[2 5 8]
[3 6 9]


In [ ]:
print(arr3[::, 1:2])  #slicing on columns
print(arr3[2::, 1:2]) #slicing on rows and columns

[[2]
 [5]
 [8]]
[[8]]
