<a href="https://colab.research.google.com/github/mukund1040/NumPy-Learning-Journey/blob/main/05_Reshaping_%26_Flattening.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
reshaped2 = arr1.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [6]:
print(reshaped2.flatten())

[1 2 3 4 5 6]
