<a href="https://colab.research.google.com/github/mukund1040/NumPy-Learning-Journey/blob/main/06_Stacking_%26_Splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Array Stacking:  combining multiple arrays along a new axis, resulting in an array with a higher dimension than the input arrays
# Array Splitting:

In [5]:
# stacking
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking - row wise          -> output array is 2D
print(np.hstack((a,b))) # horizontal stacking - column wise     -> output array is 1D

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [6]:
# splitting
c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [7]:
hsplit = np.hsplit(c,3) # horizontal split -> input and output array are same dimention

for s in hsplit:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [8]:
vsplit = np.vsplit(c,2) # vertical split -> input and output array are same dimention

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]
