<a href="https://colab.research.google.com/github/mukund1040/NumPy-Learning-Journey/blob/main/07_Mathematical_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
 import numpy as np


In [12]:

# FYI: list vs Array
# one of the reason we array instead of list : time taken by an operation on list is more >>>>> than array
%%time
numbers = list(range(1, 100000001))
result = [x+5 for x in numbers]

CPU times: user 5.5 s, sys: 4.32 s, total: 9.82 s
Wall time: 9.88 s


In [5]:
%%time
numbers = np.arange(1,100000001)
result = numbers+5

CPU times: user 2.73 s, sys: 859 ms, total: 3.59 s
Wall time: 3.61 s


In [6]:
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [7]:
print(a+10) # add a value in array
print(a-30) # subs a value in array
print(a*2) # multiply by a value in array
print(a/10) # divide by a value in array

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [8]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [9]:
print(np.square(b)) # square of all array elements
print(np.sqrt(b))   # square root of all array elements

[ 1 16 81]
[1. 2. 3.]
