<a href="https://colab.research.google.com/github/mukund1040/NumPy-Learning-Journey/blob/main/uhiuh/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [ ]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]
